name: Nodejs Dummy Project #to RUN UNIT TEST IN NODE JS PROJECT
on: push
jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nodejs #we are doing this for practice but runner comes with preinstalled software
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install Dependencies 
        run: npm ci

      - name: Run test 
        run: npm test
  deploy:  #added multiple jobs 
    needs: test   #to run jobs sequentially i.e. deploy jobs trigger only after test job gets completed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nodejs #we are doing this for practice but runner comes with preinstalled software
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install Dependencies 
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy #we don't have any server to deploy this so we are just doing echo
        run: echo "Deploying ..."
